name: 🪞 Mirror repository

on:
  push:
    branches:
      - master
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-OOP-400-NAN-4-1-tekspice-thomas.boue.git"

jobs:
  push_to_mirror:
    name: 🪞 Push to mirror
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: 🛬 Clone original repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 🛫 Upload to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}